#!/bin/bash
while read oldrev newrev ref
do
	if [[ $ref =~ .*/master$ ]];
	then
		echo "Master ref has been received. Deploying master branch to production server..."
		git --work-tree=/var/www/html --git-dir=/home/daniel2/admin checkout -f
	else
		echo "Ref $ref successfully received. Doing nothing: only the master branch may be deployed on this server."
	fi
done
